# Generated by Django 5.0.6 on 2024-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
